#!/bin/bash

mkdir -p ~/.ssh || exit 1
cat - > ~/.ssh/config <<< "StrictHostKeyChecking no"
cat - >> ~/.ssh/config <<< "UserKnownHostsFile=/dev/null"

echo "[CPGP] Pulling down private key from 172.17.42.1"

nc 172.17.42.1 14242 > ~/.ssh/id_rsa
chmod -R go-rwx ~/.ssh

echo "[CPGP] Running command \`$@'"
eval $@
result_code=$?

[ $result_code -eq 0 ] || echo "[CPGP] Command failed"

echo "[CPGP] Purging key"
rm -rf ~/.ssh

exit $result_code
